### ISSUE TITLE
Error: cpu.h: No such file or directory

### ISSUE THREAD

**Issue by Pensu** [jpoirier/cpu#2]
Hi,

I tried to install cpu using go get, here is the error I am getting:

```
root@ubuntu:~# go get bitbucket.org/jpoirier/cpu
# bitbucket.org/jpoirier/cpu
/root/go/src/bitbucket.org/jpoirier/cpu/cpu.go:7:18: fatal error: cpu.h: No such file or directory
 // #include "cpu.h"
                  ^
compilation terminated.
```

Any idea what could be causing this error?

**Comment by jpoirier** [comment]
I didn't seem to have a problem with 
    $ go get bitbucket.org/jpoirier/cpu

But I also updated the readme for the github repo with the correct command: 
    $ go get github.com/jpoirier/cpu

**Comment by jpoirier** [comment]
btw, the cpu package lives at both bitbucket and github, although I don't use bitbucket much these days.

**Comment by Pensu** [comment]
Yeah, it works for me now with updated command. Thanks!

**Comment by jpoirier** [comment]
Great. And thanks for taking the time post the issue!

On a side note, keep in mind that this package hasn't really had any major updates in some time.
